// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztihtgtxsrujfndcdpdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0aWh0Z3R4c3J1amZuZGNkcGR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMzU4NTUsImV4cCI6MjA2MDkxMTg1NX0.FOa3i6oGQR8zqp9YeADxMOn0GDQ7eH273L68W-sMWV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);